name: 샘플ARM서버배포
on:
  workflow_dispatch: 
  push:
    branches: [ "develop"]
env:
    project_location: ./Project1
    aws_region: ap-northeast-1
    function_name: test3
    dotnet_version: "10"
    discord_webhook: "https://discord.com/api/webhooks/1287816366123909133/0VEcUTlumPJEJvrBQCrnlxwhG60pM0OIYW8vtyubLnL3bS6tzWTrVhXH3HWyezlCs_4y"
    FIXTURE_INITIALIZE_DELAY: "200"
  
jobs:
  build:

    runs-on: ubuntu-24.04-arm
        
    defaults:
      run : 
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3
      name: Setup .NET

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name : Run Docker Images
      run: docker-compose -f ./docker-compose.yml up -d
      working-directory: ./

    - name: Discord Notification - Start
      run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "▶️${{github.ref}} 배포를 시작합니다.=>${{ github.event.head_commit.message }}", "allowed_mentions": {"parse": []}}' \
          ${{ env.discord_webhook }}

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.dotnet_version}}.0.x
        include-prerelease: false
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: install lambda tool
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: write version.json
      run: |
        chmod +x $project_location
        sudo echo '{
          "Workflow" : "${{github.workflow}}",
          "RunId" : "${{github.run_id}}",
          "RunNumber" : "${{github.run_number}}",
          "CommitSha" : "${{github.sha}}",
          "OS" : "${{runner.os}}",
          "Architecture" : "${{runner.arch}}",
          "CommitMessage" : "${{github.event.head_commit.message}}"
        }' > $project_location/version.json


    - name: deploy to aws lambda
      run: |
        dotnet lambda deploy-function \
        --aws-access-key-id ${{secrets.AWS_ACCESS_KEY}} \
        --aws-secret-key ${{secrets.AWS_SECRET_ACCESS_KEY}} \
        --region $aws_region \
        --configuration "Release" \
        --function-architecture "arm64" \
        --function-runtime "dotnet${{env.dotnet_version}}" \
        --function-name $function_name \
        --project-location $project_location \
        --framework "net${{env.dotnet_version}}.0" \
        --package-type "Zip" \
        --msbuild-parameters "--self-contained true"

    - name: Discord Notification - Success
      if: success()
      run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "✅${{github.ref}} 배포성공=>${{ github.event.head_commit.message }}"}' \
          ${{ env.discord_webhook }}

    - name: Discord Notification - Failure
      if: failure()
      run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "🚨🚨🚨${{github.ref}} 배포실패🚨=>${{ github.event.head_commit.message }}"}' \
          ${{ env.discord_webhook }}