name: .NET

on:
  push:
    branches: [ "main", "feature/nugetDeploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src


    - name: Pack
      run: dotnet pack --configuration Release --output ./nupkg
      working-directory: ./src/Gzzz.Server.Shared

    - name: Sleep for 3 seconds
      run: sleep 3s
      shell: bash

    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json